const TOKEN_DETAILS = {
  JWT_SECRET_KEY: "BACKENDPROJECTBYNIAMUDEEN",
  REFRESH_SECRET_KEY: "BACKENDPROJECTBYNIAMUDEEN",
  ACCESS_TOKEN_EXPIRATION_TIME: "1d",
  REFRESH_TOKEN_EXPIRATION_TIME: "7d",
};

module.exports = TOKEN_DETAILS;
